// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
const clone=value=>JSON.parse(JSON.stringify(value));
const text=(value,max=2048)=>typeof value==='string'?value.slice(0,max):'';
const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
function provenance(value){
 const v=object(value)?value:{},environment=object(v.environment)?clone(v.environment):null,audit=object(v.audit)?clone(v.audit):null;
 if(environment)for(const key of ['leanVersion','environmentHash','gitCommit'])environment[key]=typeof environment[key]==='string'?text(environment[key],2048):null;
 if(audit){audit.axioms=Array.isArray(audit.axioms)?audit.axioms.filter(item=>typeof item==='string').slice(0,256):[];delete audit.verified;delete audit.kernelAccepted;}
 return{projectId:text(v.projectId,128),target:text(v.target,512),policy:text(v.policy,80),sourceHash:typeof v.sourceHash==='string'?text(v.sourceHash,128):null,generatedCode:typeof v.generatedCode==='string'?text(v.generatedCode,128*1024):null,environment,audit,observedStatus:text(v.observedStatus,80),historical:true};
}
export function normalizeNotebook(value={}){if(!object(value))value={};return{variants:Array.isArray(value.variants)?value.variants.filter(v=>object(v)&&typeof v.name==='string'&&object(v.document)).slice(-2).map(v=>({name:text(v.name,80),document:cleanDocument(v.document),provenance:provenance(v.provenance),createdAt:text(v.createdAt,80)})):[],steps:Array.isArray(value.steps)?value.steps.filter(v=>object(v)&&typeof v.id==='string').slice(-20).map(bookmark):[]};}
function cleanDocument(document){const {review,verified,kernelAccepted,...rest}=clone(document);return rest;}
export function saveVariant(value,name,document,result){const state=normalizeNotebook(value);const origin={projectId:document.projectId??document.graph?.projectId??'glean',target:document.target??'glean_proof',policy:document.policy??document.graph?.policy??'strict',sourceHash:result?.sourceHash??null,generatedCode:result?.generatedCode??document.source??null,environment:result?.environment??null,audit:result?.audit??null,observedStatus:result?.status??'unverified',historical:true};const entry={name:text(name||'A',80),document:cleanDocument(document),provenance:provenance(origin),createdAt:new Date().toISOString()};state.variants=[...state.variants.filter(item=>item.name!==entry.name),entry].slice(-2);return state;}
export function restoreVariant(value,name){const item=normalizeNotebook(value).variants.find(item=>item.name===name);if(!item)throw new Error('저장된 문서 상태가 없습니다.');return cleanDocument(item.document);}
function observation(value){if(!object(value))return null;return{sourceIdentity:text(value.sourceIdentity,128),projectId:text(value.projectId,128),filename:text(value.filename,128),sessionId:text(value.sessionId,128),version:Number.isInteger(value.version)&&value.version>=0?value.version:null,position:{line:Number.isInteger(value.position?.line)&&value.position.line>=0?value.position.line:0,character:Number.isInteger(value.position?.character)&&value.position.character>=0?value.position.character:0},goals:Array.isArray(value.goals)?value.goals.filter(g=>typeof g==='string').slice(0,256):[],structuredGoals:Array.isArray(value.structuredGoals)?value.structuredGoals.filter(g=>object(g)&&typeof g.type==='string').slice(0,256).map(g=>({mvarId:text(g.mvarId,128),name:text(g.name,128),type:text(g.type,8192),hypotheses:Array.isArray(g.hypotheses)?g.hypotheses.filter(h=>object(h)&&typeof h.type==='string').slice(0,256).map(h=>({name:text(h.name,128),type:text(h.type,8192),fvarId:text(h.fvarId,128)})):[]})):[]};}
export function bookmark(value){return{id:text(value.id,128),name:text(value.name,128),description:text(value.description),revision:text(value.revision,128),sourceIdentity:text(value.sourceIdentity,128),scopeId:text(value.scopeId,256),nodeIds:Array.isArray(value.nodeIds)?value.nodeIds.filter(id=>typeof id==='string').slice(0,256):[],sourceRange:object(value.sourceRange)?clone(value.sourceRange):null,before:observation(value.before),after:observation(value.after),subgraph:object(value.subgraph)?clone(value.subgraph):null,source:text(value.source,8192),createdAt:text(value.createdAt??new Date().toISOString(),80)};}
export function compareVariants(value){
 const variants=normalizeNotebook(value).variants;if(variants.length!==2)return null;const [a,b]=variants,fields=[];
 const visit=(left,right,path)=>{if(JSON.stringify(left)===JSON.stringify(right))return;if(left&&right&&typeof left==='object'&&typeof right==='object'&&Array.isArray(left)===Array.isArray(right)){for(const key of new Set([...Object.keys(left),...Object.keys(right)]))visit(left[key],right[key],path?path+'.'+key:key);}else fields.push({path,before:left??null,after:right??null});};
 visit(a.document,b.document,'');const sourceText=entry=>typeof entry.provenance.generatedCode==='string'?entry.provenance.generatedCode:typeof entry.document.source==='string'?entry.document.source:null;
 const firstSource=sourceText(a),secondSource=sourceText(b),sourceComparisonAvailable=firstSource!==null&&secondSource!==null,source=[];
 if(sourceComparisonAvailable){const first=firstSource.split('\n'),second=secondSource.split('\n');for(let index=0;index<Math.max(first.length,second.length);index++)if(first[index]!==second[index])source.push({line:index+1,before:first[index]??'',after:second[index]??''});}
 const firstEnvironment=a.provenance.environment?.environmentHash,secondEnvironment=b.provenance.environment?.environmentHash,environmentComparisonAvailable=Boolean(firstEnvironment&&secondEnvironment);
 return{names:[a.name,b.name],fields,source,sourceComparisonAvailable,environmentComparisonAvailable,environmentChanged:environmentComparisonAvailable?firstEnvironment!==secondEnvironment:null,policyChanged:a.provenance.policy!==b.provenance.policy};
}
