import test from 'node:test';
import assert from 'node:assert/strict';
import {containerBounds,normalizePresentation,scopeIndex,semanticDocument,PresentationSession,projectScope,createContainer,moveContainer,setManualHidden,occurrenceView,occurrenceKey,prunePresentation} from './presentation.mjs';
import {semanticKey} from './history.mjs';

const graph=()=>({version:3,name:'chain',projectId:'glean',imports:[],policy:'strict',inputs:[],goal:'True',nodes:['A','B','C','D'].map((id,i)=>({id,kind:'script',name:id,inputs:i?[{id:'x',name:'x',type:'True'}]:[],outputType:'True',body:i?'x':'True.intro',x:i*230,y:80})),edges:[{id:'ab',source:'A',output:'out',target:'B',input:'x'},{id:'bc',source:'B',output:'out',target:'C',input:'x'}],result:{node:'C',output:'out'},modules:[]});
const fresh=()=>normalizePresentation({kind:'graph',graph:graph()}).value;
test('semantic deletion removes stale saved IDs while keeping the original undo snapshot intact',()=>{const doc={kind:'graph',graph:graph()};doc.presentation=fresh();createContainer(doc.graph,doc.presentation.scopes.root,['n:B'],{id:'g',name:'g'});setManualHidden(doc.presentation.scopes.root,null,['n:B'],true);const previous=structuredClone(doc);doc.graph.nodes=doc.graph.nodes.filter(n=>n.id!=='B');prunePresentation(doc);assert.deepEqual(doc.presentation.scopes.root.hidden,[]);assert.deepEqual(doc.presentation.scopes.root.containers[0].children,[]);assert.equal(normalizePresentation(doc).warnings.length,0);assert.deepEqual(previous.presentation.scopes.root.hidden,['n:B']);});
test('presentation and runtime navigation never change the semantic key or compiler document',()=>{const doc={kind:'graph',graph:graph()},shown={...doc,presentation:fresh(),sessionView:{root:{targets:['A']}},analysisCache:{status:'valid'},navigationState:{zoom:.2}};shown.presentation.scopes.root.hidden=['n:B'];assert.equal(semanticKey(doc),semanticKey(shown));assert.deepEqual(semanticDocument(shown),semanticDocument(doc));shown.graph={...shown.graph,nodes:shown.graph.nodes.map(n=>n.id==='B'?{...n,body:'by sorry'}:n)};assert.notEqual(semanticKey(doc),semanticKey(shown));});
test('legacy groups migrate without changing proof nodes and malformed trees are quarantined',()=>{const body=graph();body.version=2;body.groups=[{id:'old',name:'old',nodeIds:['A','B'],collapsed:true,x:0,y:0}];const doc={kind:'graph',graph:body},migrated=normalizePresentation(doc);assert.deepEqual(migrated.value.scopes.root.containers[0].children,['n:A','n:B']);assert.deepEqual(doc.graph.nodes,body.nodes);const malformed={version:1,scopes:{root:{hidden:['n:missing'],containers:[{id:'one',name:'one',children:['c:two','n:A'],collapsed:true,x:0,y:0},{id:'two',name:'two',children:['c:one','n:A'],collapsed:true,x:0,y:0}]}}};const repaired=normalizePresentation({...doc,presentation:malformed});assert.ok(repaired.warnings.length);assert.deepEqual(repaired.original,malformed);assert.doesNotThrow(()=>projectScope(body,repaired.value.scopes.root));});
test('manual hiding preserves each actual edge and never invents A to C',()=>{const body=graph(),p=fresh().scopes.root;setManualHidden(p,null,['n:B'],true);const view=projectScope(body,p);assert.ok(!view.nodes.some(n=>n.id==='B'));const boundary=view.nodes.find(n=>n.hiddenBoundary&&n.realNodeId==='B');assert.ok(boundary);assert.deepEqual(view.edges.map(e=>[e.id,e.originalSource,e.originalTarget]),[['ab','A','B'],['bc','B','C']]);assert.ok(!view.edges.some(e=>e.source==='A'&&e.target==='C'));setManualHidden(p,null,['n:D'],true);assert.ok(!projectScope(body,p).nodes.some(n=>n.realNodeId==='D'));});
test('isolation renders only direct hidden boundaries and no hidden-to-hidden wires',()=>{const body=graph(),p=fresh().scopes.root,s=new PresentationSession();s.isolate('root',body,p,['n:C'],{});const view=projectScope(body,p,s.state('root'));assert.deepEqual(view.nodes.filter(n=>n.hiddenBoundary).map(n=>n.realNodeId),['B']);assert.deepEqual(view.edges.map(e=>e.id),['bc']);assert.deepEqual(body.edges.map(e=>e.id),['ab','bc']);});
test('proxy ports encode node and port tuples without delimiter collisions',()=>{const body={nodes:[{id:'A:x',kind:'script',inputs:[{id:'y'}]},{id:'A',kind:'script',inputs:[{id:'x:y'}]}],edges:[]},p={hidden:[],containers:[{id:'g',name:'g',children:['n:A:x','n:A'],collapsed:true,x:0,y:0}]};const ports=projectScope(body,p).nodes[0].inputPorts;assert.equal(new Set(ports.map(p=>p.id)).size,2);});
test('isolation freezes selection, deduplicates stages and restores viewport without overwriting hides',()=>{const body=graph(),p=fresh().scopes.root,s=new PresentationSession();assert.equal(s.isolate('root',body,p,[],{x:1,y:2,zoom:.8}),false);s.isolate('root',body,p,['n:A','n:C'],{x:1,y:2,zoom:.8});s.isolate('root',body,p,['n:A','n:C'],{x:9,y:9,zoom:.2});assert.equal(s.state('root').frames.length,1);assert.deepEqual(projectScope(body,p,s.state('root')).visibleIds,['A','C']);setManualHidden(p,s.state('root'),['n:A'],true);s.isolate('root',body,p,['n:C'],{x:3,y:4,zoom:1});assert.equal(s.state('root').frames.length,2);assert.deepEqual(s.back('root'),{x:3,y:4,zoom:1});assert.deepEqual(s.exit('root'),{x:1,y:2,zoom:.8});assert.deepEqual(p.hidden,['n:A']);});
test('adding a hidden item bypasses earlier frames but newest manual Hide defeats all overrides',()=>{const body=graph(),p=fresh().scopes.root,s=new PresentationSession();setManualHidden(p,null,['n:D'],true);s.isolate('root',body,p,['n:A'],{});s.isolate('root',body,p,['n:C'],{});s.add('root',body,p,['n:D'],true);assert.deepEqual(projectScope(body,p,s.state('root')).visibleIds,['C','D']);setManualHidden(p,s.state('root'),['n:D'],true);assert.deepEqual(projectScope(body,p,s.state('root')).visibleIds,['C']);s.back('root');assert.deepEqual(projectScope(body,p,s.state('root')).visibleIds,['A']);assert.deepEqual(p.hidden,['n:D']);});
test('temporary diagnostics open ancestors without mutating collapse or isolation',()=>{const body=graph(),p=fresh().scopes.root;createContainer(body,p,['n:B'],{id:'inner',name:'inner'});createContainer(body,p,['c:inner','n:C'],{id:'outer',name:'outer'});const s=new PresentationSession();s.isolate('root',body,p,['n:A'],{});const original=JSON.stringify(p);s.reveal('root',body,p,'B');assert.ok(projectScope(body,p,s.state('root')).nodes.some(n=>n.id==='B'));assert.equal(JSON.stringify(p),original);s.clearTemporary('root');assert.ok(!projectScope(body,p,s.state('root')).nodes.some(n=>n.id==='B'));});
test('nested containers preserve endpoint proxies and movement is reversible with all descendants',()=>{const body=graph(),p=fresh().scopes.root;createContainer(body,p,['n:B'],{id:'one',name:'one'});createContainer(body,p,['c:one'],{id:'two',name:'two'});createContainer(body,p,['c:two'],{id:'three',name:'three'});const view=projectScope(body,p);const cap=view.nodes.find(n=>n.containerId==='three');assert.ok(cap);assert.deepEqual(cap.memberIds,['B']);assert.equal(view.edges[0].originalTarget,'B');assert.equal(cap.inputPorts[0].nodeId,'B');const before=JSON.stringify({body,p});moveContainer(body,p,'three',20,30);assert.equal(body.nodes.find(n=>n.id==='B').x,250);moveContainer(body,p,'three',-20,-30);assert.equal(JSON.stringify({body,p}),before);assert.throws(()=>createContainer(body,p,['n:B'],{id:'bad',name:'bad'}));});
test('scope and occurrence identities do not share call A/B or Cases branch display state',()=>{const body=graph();body.modules=[{id:'M',nodes:[],edges:[]}];body.nodes.push({id:'case',kind:'cases',branches:[{id:'left',nodes:[],edges:[]},{id:'right',nodes:[],edges:[]}]});assert.ok(scopeIndex({kind:'graph',graph:body}).has('root/case/left'));const s=new PresentationSession();s.isolate('root/call:A/module:M',graph(),fresh().scopes.root,['n:A'],{});assert.equal(s.state('root/call:B/module:M').frames.length,0);assert.equal(s.state('root/case/left').frames.length,0);});
test('new entities join the current isolation and removing all targets safely ends it',()=>{const body=graph(),p=fresh().scopes.root,s=new PresentationSession();s.isolate('root',body,p,['n:A'],{});body.nodes.push({id:'new',kind:'nat',value:'1',x:0,y:0});s.includeNew('root',['new']);assert.ok(projectScope(body,p,s.state('root')).visibleIds.includes('new'));body.nodes=body.nodes.filter(n=>!['A','new'].includes(n.id));s.prune('root',body,p);assert.equal(s.state('root').frames.length,0);});
test('manual occurrence views are detached from each other and validated on reload',()=>{const root=graph();root.modules=[{id:'M',...graph()}];root.nodes.push({id:'callA',kind:'module',ref:'M'},{id:'callB',kind:'module',ref:'M'});const doc={kind:'graph',graph:root},p=normalizePresentation(doc).value;const ta=[{scopeId:'root',nodeId:'callA',definitionId:'M'}],tb=[{scopeId:'root',nodeId:'callB',definitionId:'M'}],ka=occurrenceKey('module/M',ta),kb=occurrenceKey('module/M',tb),a=occurrenceView(p,ka,'module/M',ta),b=occurrenceView(p,kb,'module/M',tb);setManualHidden(a,null,['n:B'],true);assert.deepEqual(b.hidden,[]);assert.deepEqual(p.scopes['module/M'].hidden,[]);const restored=normalizePresentation({...doc,presentation:JSON.parse(JSON.stringify(p))});assert.deepEqual(restored.value.occurrenceViews[ka].view.hidden,['n:B']);assert.deepEqual(restored.value.occurrenceViews[kb].view.hidden,[]);p.occurrenceViews[ka].trail[0].nodeId='missing';assert.ok(normalizePresentation({...doc,presentation:p}).warnings.length);});
test('manual hiding the last temporary diagnostic restores the original collapsed ancestor',()=>{const body=graph(),p=fresh().scopes.root;createContainer(body,p,['n:B','n:C'],{id:'group',name:'group'});const s=new PresentationSession();s.reveal('root',body,p,'B');assert.ok(projectScope(body,p,s.state('root')).nodes.some(n=>n.id==='C'));setManualHidden(p,s.state('root'),['n:B'],true);assert.deepEqual(s.state('root').temporary.expanded,[]);assert.ok(!projectScope(body,p,s.state('root')).nodes.some(n=>n.id==='C'));});
test('empty imported containers never generate nonfinite wrapping coordinates',()=>{const body=graph(),p=fresh().scopes.root;p.containers.push({id:'empty',name:'empty',children:[],collapsed:true,x:0,y:0});assert.throws(()=>createContainer(body,p,['c:empty'],{id:'wrap',name:'wrap'}));assert.ok(p.containers.every(c=>Number.isFinite(c.x)&&Number.isFinite(c.y)));});
test('ignored script metadata cannot make semantic-scope traversal crash',()=>{const body=graph();body.nodes[0].branches=42;assert.doesNotThrow(()=>normalizePresentation({kind:'graph',graph:body}));assert.equal(scopeIndex({kind:'graph',graph:body}).size,1);});
test('malformed scope records and overflow both preserve recovery evidence',()=>{const doc={kind:'graph',graph:graph()};for(const raw of ['broken',{hidden:[],containers:Array.from({length:257},(_,i)=>({id:'c'+i,name:'c'+i,children:[],collapsed:false,x:0,y:0}))}]){const presentation={version:1,scopes:{root:raw}};const normalized=normalizePresentation({...doc,presentation});assert.ok(normalized.warnings.length);assert.deepEqual(normalized.original,presentation);}});

test('occurrence corruption, excess entries and mismatched key associations retain recovery',()=>{const root=graph();root.modules=[{id:'M',...graph()}];root.nodes.push({id:'callA',kind:'module',ref:'M'},{id:'callB',kind:'module',ref:'M'});const doc={kind:'graph',graph:root},ta=[{scopeId:'root',nodeId:'callA',definitionId:'M'}],tb=[{scopeId:'root',nodeId:'callB',definitionId:'M'}];for(const views of ['broken',Object.fromEntries(Array.from({length:257},(_,i)=>['k'+i,{scopeId:'module/M',trail:ta,view:{hidden:[],containers:[]}}])),{[occurrenceKey('module/M',ta)]:{scopeId:'module/M',trail:tb,view:{hidden:['n:B'],containers:[]}}}]){const p={version:1,scopes:{},occurrenceViews:views},normalized=normalizePresentation({...doc,presentation:p});assert.ok(normalized.warnings.length);assert.deepEqual(normalized.original,p);}const p=normalizePresentation(doc).value,key=occurrenceKey('module/M',ta);p.occurrenceViews[key]={scopeId:'module/M',trail:tb,view:{hidden:['n:B'],containers:[]}};assert.throws(()=>occurrenceView(p,key,'module/M',ta));});
test('expanded nested bounds reserve distinct container headings at every level',()=>{const body=graph(),p=fresh().scopes.root;for(const [id,children] of [['one',['n:B']],['two',['c:one']],['three',['c:two']]]){createContainer(body,p,children,{id,name:id});p.containers.at(-1).collapsed=false;}const rects=containerBounds(p,projectScope(body,p).nodes,n=>({width:190,height:110}));assert.equal(rects.get('one').y,38);assert.equal(rects.get('two').y,-4);assert.equal(rects.get('three').y,-46);assert.ok(rects.get('three').width>rects.get('two').width);});
