// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import test from 'node:test';import assert from 'node:assert/strict';
import {sourceScope,sourceRelations,sourceView,normalizeSourceDeclarations} from './source-view.mjs';
import {setManualHidden,PresentationSession,projectScope,createContainer,semanticDocument} from './presentation.mjs';
const declarations=[{name:'N.a',directDependencies:['Nat.add_zero']},{name:'N.b',directDependencies:['N.a']},{name:'N.c',directDependencies:['N.b']}];
test('source relations expose actual direct names without inventing editable proof wires',()=>{const body=sourceScope({filename:'File.lean'},declarations);assert.equal(body.edges.length,0);assert.equal(body.nodes.length,4);assert.deepEqual(sourceRelations(declarations,['declaration:N.b'],'inputs'),{ids:['declaration:N.a'],unresolved:[]});assert.deepEqual(sourceRelations(declarations,['declaration:N.a'],'inputs'),{ids:[],unresolved:['Nat.add_zero']});assert.deepEqual(sourceRelations(declarations,['declaration:N.a'],'users'),{ids:['declaration:N.b'],unresolved:[]});});
test('file and declarations share Hide/containers while source bytes and semantic identity remain exact',()=>{const doc={kind:'lean',filename:'File.lean',source:'namespace N\r\nend N\r\n',projectId:'glean',target:'',analysisCache:{declarations}},body=sourceScope(doc,declarations),normalized=sourceView(doc,declarations),p=normalized.value.scopes.root,session=new PresentationSession();const before=semanticDocument(doc);createContainer(body,p,['n:declaration:N.a','n:declaration:N.b'],{id:'group',name:'helpers'});setManualHidden(p,session.state('root'),['n:file'],true);doc.sourceFileView={version:1,presentation:normalized.value};assert.deepEqual(semanticDocument(doc),before);const saved=JSON.parse(JSON.stringify(doc));assert.equal(saved.source,doc.source);const restored=sourceView(saved,declarations);assert.deepEqual(restored.value,normalized.value);assert.deepEqual(projectScope(body,p,session.state('root')).hiddenIds,['file']);});
test('a thousand source declarations have their own analysis view and no semantic graph node cap',()=>{const data=Array.from({length:1000},(_,i)=>({name:'N.t'+i,directDependencies:[]}));assert.equal(sourceScope({filename:'File.lean'},data).nodes.length,1001);assert.deepEqual(sourceView({filename:'File.lean'},data).warnings,[]);});
test('unknown source view wrappers are quarantined with exact original and safe default visibility',()=>{const presentation={version:1,scopes:{root:{hidden:['n:file'],containers:[]}},occurrenceViews:{}};for(const original of ['broken',{version:99,presentation},{version:1}]){const result=sourceView({filename:'File.lean',sourceFileView:original});assert.ok(result.warnings.length);assert.deepEqual(result.original,original);assert.deepEqual(result.value.scopes.root.hidden,[]);}});
test('historical analysis rejects malformed optional imports, ranges and dependency provenance without mutating cache',()=>{const base={adapter:'Lean command state',imports:['Init'],environment:{environmentHash:'a'.repeat(64)},declarations:[{name:'N.a',kind:'thm',inputs:[],outputType:'True',directDependencies:[],dependencyModules:{},range:{startLine:1,startCharacter:0,endLine:1,endCharacter:5}}]};assert.equal(normalizeSourceDeclarations(base),base);for(const edit of [c=>c.imports=42,c=>c.imports=[{}],c=>c.declarations[0].range='broken',c=>c.declarations[0].range.endLine=0,c=>c.declarations[0].dependencyModules=[],c=>c.environment=42]){const cache=structuredClone(base);edit(cache);const original=structuredClone(cache);assert.equal(normalizeSourceDeclarations(cache),null);assert.deepEqual(cache,original);}});
