// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import test from 'node:test';import assert from 'node:assert/strict';
import {initSourceAnalysis} from './source-analysis.mjs';
class Element{
 constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.value='';this.className='';this.style={};this.dataset={};this.listeners={};this.attrs={};this.classList={toggle(){}};}
 append(...items){for(const item of items){item.parentElement=this;this.children.push(item);}}replaceChildren(...items){this.children=[];this.append(...items);}addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}setAttribute(key,value){this.attrs[key]=value;}closest(){return null;}
 async trigger(type,fields={}){for(const fn of this.listeners[type]??[])await fn({target:this,preventDefault(){},stopPropagation(){},...fields});}
}
const all=n=>[n,...n.children.flatMap(all)],find=(n,text)=>all(n).find(item=>item.textContent===text);
const data={adapter:'test controlled command-state result',status:'analyzed',imports:['Init','Init'],sourceHash:'a'.repeat(64),filename:'File.lean',projectId:'glean',environment:{environmentHash:'b'.repeat(64)},declarations:[{name:'N.a',kind:'Lean.ConstantKind.thm',isProp:true,universes:[],inputs:[],outputType:'True',directDependencies:Array.from({length:200},(_,i)=>'Installed.'+i),range:{startLine:1,startCharacter:0,endLine:1}},{name:'N.b',kind:'Lean.ConstantKind.thm',isProp:true,universes:[],inputs:[],outputType:'True',directDependencies:['N.a'],range:{startLine:2,startCharacter:0,endLine:2}}]};
function harness(origin,route){globalThis.document={createElement:t=>new Element(t)};let doc={kind:'lean',source:'theorem a : True := True.intro\n',filename:'File.lean',projectId:'glean',target:'',sourceOrigin:origin};const host=new Element(),fileCard=new Element('article'),status=new Element(),run=new Element('button'),cancel=new Element('button'),calls=[],converted=[];const analysis=initSourceAnalysis({host,fileCard,status,run,cancel,current:()=>structuredClone(doc),onCache:value=>doc.analysisCache=value,onView:value=>doc.sourceFileView=value,jump(){},onReference(){},onConvert:(value,original)=>converted.push({value,original}),post:async(url,body)=>{calls.push({url,body});return route?route(url,body):structuredClone(data);}});return{host,fileCard,status,run,cancel,analysis,calls,converted,current:()=>doc};}
test('source file alone can be hidden, grouped and expanded while original source remains exact',async()=>{const h=harness();try{h.analysis.loadCache(null);await h.fileCard.trigger('click');await find(h.host,'그룹으로 묶기').trigger('click');assert.equal(h.fileCard.hidden,true);assert.ok(all(h.host).some(n=>n.className.startsWith('source-container-card')));await find(h.host,'펼치기').trigger('click');assert.equal(h.fileCard.hidden,false);await h.fileCard.trigger('click');await find(h.host,'선택 숨기기').trigger('click');assert.equal(h.fileCard.hidden,true);assert.equal(h.current().source,'theorem a : True := True.intro\n');await find(h.host,'수동 숨김 해제').trigger('click');assert.equal(h.fileCard.hidden,false);}finally{h.analysis.close();}});
test('actual declarations keep raw names and all metadata while installation dependencies render in pages of fifty',async()=>{const h=harness();try{h.analysis.loadCache(null);await h.run.trigger('click');const imports=all(h.host).find(n=>n.attrs['aria-label']==='설치 선언 조회 import 모듈');assert.equal(imports.value,'Init');assert.ok(all(h.host).some(n=>n.textContent==='설치 환경 직접 참조 200개'));assert.equal(all(h.host).filter(n=>n.tagName==='button'&&n.textContent.includes(' · 설치 환경')).length,50);assert.equal(h.current().analysisCache.declarations[0].directDependencies.length,200);assert.ok(all(h.host).some(n=>n.textContent.startsWith('정리 · 현재 파일')));await find(h.host,'직접 참조 더 보기 (50/200)').trigger('click');assert.equal(all(h.host).filter(n=>n.tagName==='button'&&n.textContent.includes(' · 설치 환경')).length,100);h.analysis.loadCache(h.current().analysisCache);assert.ok(h.status.textContent.includes('저장된'));assert.ok(all(h.host).filter(n=>n.textContent==='원문 위치').every(n=>n.disabled));}finally{h.analysis.close();}});
test('invalid UTF8 original never enables analysis after cache reload or cancellation',async()=>{const h=harness({decoding:'invalid-utf8'});h.current().source='';try{h.analysis.loadCache(null);assert.equal(h.run.disabled,true);await h.run.trigger('click');assert.equal(h.calls.length,0);await h.cancel.trigger('click');assert.equal(h.run.disabled,true);}finally{h.analysis.close();}});

test('historical installed lookup failure cannot overwrite a subsequently edited source',async()=>{let reject;const h=harness(undefined,url=>url.endsWith('/declaration')?new Promise((_,r)=>reject=r):structuredClone(data));try{h.analysis.loadCache(data);const request=find(h.host,'설치 환경의 같은 이름 조회').trigger('click');while(!reject)await new Promise(r=>setTimeout(r,0));h.current().source='theorem newer : True := True.intro';h.analysis.invalidate();reject(new Error('obsolete lookup failure'));await request;assert.ok(!h.status.textContent.includes('obsolete'));assert.ok(h.status.textContent.includes('미확정'));}finally{h.analysis.close();}});
test('malformed historical imports leave original source and cache saved while loading the safe file view',()=>{const h=harness(),cache={...structuredClone(data),imports:42};h.current().analysisCache=cache;try{h.analysis.loadCache(cache);assert.equal(h.fileCard.hidden,false);assert.ok(h.status.textContent.includes('손상'));assert.equal(h.current().source,'theorem a : True := True.intro\n');assert.deepEqual(h.current().analysisCache,cache);assert.equal(h.calls.length,0);}finally{h.analysis.close();}});

test('fresh theorem conversion uses server job identity and preserves the source without treating dependencies as wires',async()=>{const h=harness(undefined,(url,body)=>url.endsWith('/convert')?{kind:'graph',graph:{sourceContext:{source:h.current().source}}}:{...structuredClone(data),jobId:'real-analysis'});try{await h.run.trigger('click');const control=find(h.host,'이 선언을 GLEAN 그래프로 변환');assert.equal(control.disabled,false);await control.trigger('click');assert.equal(h.converted.length,1);const request=h.calls.find(c=>c.url.endsWith('/convert'));assert.equal(request.body.jobId,'real-analysis');assert.equal(request.body.sourceHash,data.sourceHash);assert.equal(request.body.environmentHash,data.environment.environmentHash);assert.ok(!Object.hasOwn(request.body,'inputs'));assert.equal(h.converted[0].original.source,h.current().source);h.analysis.loadCache(data);assert.ok(all(h.host).filter(n=>n.textContent==='이 선언을 GLEAN 그래프로 변환').every(n=>n.disabled));}finally{h.analysis.close();}});
test('late conversion cannot replace a newer source and errored partial analysis cannot convert',async()=>{let resolve;const h=harness(undefined,url=>url.endsWith('/convert')?new Promise(r=>resolve=r):{...structuredClone(data),jobId:'real-analysis'});try{await h.run.trigger('click');const request=find(h.host,'이 선언을 GLEAN 그래프로 변환').trigger('click');while(!resolve)await new Promise(r=>setTimeout(r,0));h.current().source+='-- edited';h.analysis.invalidate();resolve({kind:'graph'});await request;assert.equal(h.converted.length,0);h.analysis.loadCache({...data,hasErrors:true});assert.ok(all(h.host).filter(n=>n.textContent==='이 선언을 GLEAN 그래프로 변환').every(n=>n.disabled));}finally{h.analysis.close();}});
