import test from 'node:test';import assert from 'node:assert/strict';
import {typedCompatibility,connectTyped, batchCalls, editSignature, exactNat, checkTypedImport,copyTyped,pasteTyped} from './typed-model.mjs';
const graph=()=>({version:3,name:'demo',projectId:'glean',imports:[],inputs:[],goal:'True',nodes:[],edges:[],modules:[],result:null});
test('Nat retains values beyond JS safe integer range and rejects invalid forms',()=>{assert.equal(exactNat('9007199254740993'),'9007199254740993');for(const x of ['01','-1','1.2',1])assert.throws(()=>exactNat(x));});
test('Map Zip Product expand actual calls with stable provenance and reject zip mismatch atomically',()=>{const g=graph();const left=['a','b','c'].map(node=>({node,output:'out'})),right=['d','e'].map(node=>({node,output:'out'}));for(const item of [...left,...right])g.nodes.push({id:item.node,kind:'nat',value:'1'});const call={kind:'script',inputs:[{id:'x',name:'x',type:'Nat'}],outputType:'Nat',body:'x'};const map=batchCalls(g,call,'map',left,[],['x'],'map');assert.equal(map.length,3);assert.equal(map[1].provenance.items[0].node,'b');const pair={...call,inputs:[...call.inputs,{id:'y',name:'y',type:'Nat'}]};const before=JSON.stringify(g);assert.throws(()=>batchCalls(g,pair,'zip',left,right,['x','y'],'zip'));assert.equal(JSON.stringify(g),before);assert.equal(batchCalls(g,pair,'product',right,left,['x','y'],'prod').length,6);assert.equal(batchCalls(g,pair,'zip',left,left,['x','y'],'zip').length,3);});
test('signature changes identify direct and transitive callsites without deleting wires',()=>{const g=graph();g.modules=[{id:'m',name:'M',inputs:[{id:'n',name:'n',type:'Nat'}],outputType:'Nat',nodes:[],edges:[]},{id:'outer',name:'Outer',inputs:[],outputType:'Nat',nodes:[{id:'nested',kind:'module',ref:'m'}],edges:[]}];g.nodes=[{id:'one',kind:'module',ref:'m'},{id:'two',kind:'module',ref:'m'},{id:'three',kind:'module',ref:'outer'}];assert.deepEqual(editSignature(g,'m',[{id:'n',name:'n',type:'Nat'},{id:'h',name:'h',type:'Fin n'}],'Fin n').sort(),['module/outer/nested','root/one','root/three','root/two']);assert.equal(g.modules[0].inputs[1].type,'Fin n');});
test('typed candidate hints separate current concrete type matches, rigid conflicts and uncertainty',()=>{assert.equal(typedCompatibility('Nat','Nat'),'compatible');assert.equal(typedCompatibility('Nat','Bool'),'incompatible');assert.equal(typedCompatibility(null,'Nat'),'unknown');assert.equal(typedCompatibility('Fin 3','Fin n'),'unknown');assert.equal(typedCompatibility('Alias','Nat'),'unknown');});
test('batch calls enforce the whole document node budget before mutating nested scopes',()=>{const body={id:'m',inputs:[],outputType:'Nat',nodes:[{id:'a',kind:'nat',value:'0'}],edges:[],result:{node:'a',output:'out'}},root={nodes:Array.from({length:253},(_,i)=>({id:'n'+i,kind:'nat',value:'0'})),edges:[],modules:[body]},prototype={id:'s',kind:'script',inputs:[{id:'x',name:'x',type:'Nat'}],outputType:'Nat',body:'x'};const before=JSON.stringify(root);assert.throws(()=>batchCalls(body,prototype,'map',Array.from({length:3},()=>({node:'a',output:'out'})),[],['x'],'batch',root),/제한/);assert.equal(JSON.stringify(root),before);});
test('copy/paste retains internal wires, uses fresh IDs and rejects scope/limit changes atomically',()=>{
 const g=graph();g.nodes=[{id:'a',kind:'nat',value:'3',x:0,y:0},{id:'b',kind:'script',inputs:[{id:'x',name:'x',type:'Nat'}],outputType:'Nat',body:'x',x:230,y:0}];g.edges=[{id:'ab',source:'a',output:'out',target:'b',input:'x'}];let count=0;const allocate=kind=>kind+(++count),clip=copyTyped(g,['a','b'],{documentId:'doc',scopeId:'root'});
 const created=pasteTyped(g,g,clip,{documentId:'doc',scopeId:'root'},allocate);assert.equal(created.length,2);assert.notEqual(created[0].id,'a');assert.equal(g.edges.at(-1).source,created[0].id);assert.equal(g.edges.at(-1).target,created[1].id);const before=JSON.stringify(g);assert.throws(()=>pasteTyped(g,g,clip,{documentId:'doc',scopeId:'module/M'},allocate),/범위/);assert.equal(JSON.stringify(g),before);
 g.nodes.push(...Array.from({length:251},(_,i)=>({id:'spare'+i,kind:'nat',value:'0'})));const bounded=JSON.stringify(g);assert.throws(()=>pasteTyped(g,g,clip,{documentId:'doc',scopeId:'root'},allocate),/한도/);assert.equal(JSON.stringify(g),bounded);
});
