// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
export const typedKinds=['input','nat','script','reference','module','construct','calc','cases'];
export const typedInputs=(node,graph)=>node.kind==='module'?(graph.modules.find(m=>m.id===node.ref)?.inputs??[]):(node.inputs??[]);
export const typedOutputs=node=>node.kind==='construct'?(node.outputs??[]):[{id:'out',name:'out'}];
export function exactNat(value){if(typeof value!=='string'||!/^(0|[1-9][0-9]{0,199})$/.test(value))throw new Error('Nat은 200자리 이하의 정확한 십진수 문자열이어야 합니다.');return value;}
export function checkTypedImport(graph){
 const string=v=>typeof v==='string',parameters=v=>Array.isArray(v)&&v.length<=16&&v.every(p=>p&&string(p.id)&&string(p.name)&&string(p.type));
 if(!graph||graph.version!==3||!['glean','mathlib'].includes(graph.projectId)||!string(graph.name)||!string(graph.goal)||!parameters(graph.inputs)||!Array.isArray(graph.imports)||graph.imports.length>16||!graph.imports.every(string)||!Array.isArray(graph.modules)||graph.modules.length>32)return '타입 그래프 형식을 확인하세요.';
 const c=graph.sourceContext;
 if(c!==undefined&&(!c||c.version!==1||c.module!=='GleanUploadedSource'||c.projectId!==graph.projectId||!['standard','strict'].includes(c.policy??'standard')||typeof c.source!=='string'||!c.source.trim()||new TextEncoder().encode(c.source).length>8*1024*1024||typeof c.filename!=='string'||!c.filename.endsWith('.lean')||c.filename.length>120||/[\/\\\x00-\x1f]/.test(c.filename)||typeof c.sourceHash!=='string'||!/^[a-f0-9]{64}$/.test(c.sourceHash)||typeof c.environmentHash!=='string'||!/^[a-f0-9]{64}$/.test(c.environmentHash)))return '보존된 Lean 원문 모듈 및 출처를 확인하세요.';
 for(const module of graph.modules)if(!module||!string(module.id)||!string(module.name)||!string(module.outputType)||!parameters(module.inputs))return '함수 시그니처 형식을 확인하세요.';
 let count=0,edges=0;const scopes=[[graph,0],...graph.modules.map(m=>[m,0])];while(scopes.length){const [scope,depth]=scopes.pop();if(!scope||depth>8||!Array.isArray(scope.nodes)||!Array.isArray(scope.edges))return '그래프 범위 형식을 확인하세요.';count+=scope.nodes.length;edges+=scope.edges.length;if(count>256||edges>512)return '최대 256개 노드, 512개 연결을 지원합니다.';
 if(scope.result!=null&&(!string(scope.result.node)||!string(scope.result.output)))return '결과 포트 형식을 확인하세요.';
 if(scope.edges.some(e=>!e||!['id','source','target','input','output'].every(k=>string(e[k]))))return '연결 형식을 확인하세요.';
 const ids=new Set();for(const node of scope.nodes){if(!node||!string(node.id)||ids.has(node.id)||!typedKinds.includes(node.kind))return '중복 ID 또는 알 수 없는 노드입니다.';ids.add(node.id);
 if(['input','module'].includes(node.kind)&&!string(node.ref))return '입력/함수 참조가 필요합니다.';
 if(!['input','nat','module'].includes(node.kind)&&(!parameters(node.inputs)||!string(node.outputType)))return '명시적 입력과 출력 타입이 필요합니다.';
 if(['script','construct'].includes(node.kind)&&!string(node.body))return 'Lean 본문이 필요합니다.';
 if(node.kind==='reference'&&!string(node.declaration))return 'Lean 선언 이름이 필요합니다.';
 if(node.kind==='construct'&&(!Array.isArray(node.outputs)||node.outputs.length>16||node.outputs.some(o=>!o||!['id','name','type','term'].every(k=>string(o[k])))))return '이름 있는 출력 형식을 확인하세요.';
 if(node.kind==='calc'&&(!string(node.start)||!Array.isArray(node.steps)||node.steps.length>32||node.steps.some(s=>!s||!['id','relation','term','proof'].every(k=>string(s[k])))))return 'Calc 단계 형식을 확인하세요.';
 if(node.kind==='cases'){if(!Array.isArray(node.branches)||node.branches.length>16||node.branches.some(b=>!b||!string(b.id)||!string(b.constructor)||!parameters(b.binders)))return '분기 형식을 확인하세요.';scopes.push(...node.branches.map(b=>[b,depth+1]));}
 if(node.kind==='nat'&&(!string(node.value)||node.value.length>200))return 'Nat 입력을 문자열로 저장하세요.';
 }}return null;
}
export function connectTyped(scope,graph,source,output,target,input,id){const from=scope.nodes.find(n=>n.id===source),to=scope.nodes.find(n=>n.id===target);if(!from||!to||!typedOutputs(from).some(p=>p.id===output)||!typedInputs(to,graph).some(p=>p.id===input))throw new Error('같은 범위의 유효한 포트를 선택하세요.');const remaining=scope.edges.filter(e=>e.target!==target||e.input!==input),seen=new Set(),pending=[target];while(pending.length){const current=pending.pop();if(current===source)throw new Error('순환 연결은 허용되지 않습니다.');if(seen.has(current))continue;seen.add(current);pending.push(...remaining.filter(e=>e.source===current).map(e=>e.target));}scope.edges=[...remaining,{id,source,output,target,input}];}
export function batchCalls(graph,prototype,operation,left,right,ports,prefix,rootGraph=graph){if(!['map','zip','product'].includes(operation))throw new Error('명시적인 배치 방식을 선택하세요.');if(!left.length||operation!=='map'&&!right.length)throw new Error('배치 입력이 비어 있습니다.');if(operation==='zip'&&left.length!==right.length)throw new Error('Zip 입력 길이가 다릅니다. 항목을 복제하거나 자르지 않습니다.');const pairs=operation==='map'?left.map(a=>[a]):operation==='zip'?left.map((a,i)=>[a,right[i]]):left.flatMap(a=>right.map(b=>[a,b]));const counts=bodies=>bodies.reduce((sum,[,body])=>({nodes:sum.nodes+body.nodes.length,edges:sum.edges+body.edges.length}),{nodes:0,edges:0}),current=counts(typedScopes(rootGraph)),addition=counts(typedScopes({nodes:[prototype],edges:[],modules:[]}));if(current.nodes+pairs.length*addition.nodes>256||current.edges+pairs.length*(addition.edges+ports.length)>512)throw new Error('배치 결과가 문서 크기 제한을 초과합니다.');const copy=structuredClone(graph),created=[];for(const [index,items] of pairs.entries()){const node={...structuredClone(prototype),id:prefix+'_'+index,x:380+(index%4)*210,y:80+Math.floor(index/4)*170,provenance:{operation,operationId:prefix,items:structuredClone(items)}};if(copy.nodes.some(n=>n.id===node.id))throw new Error('배치 ID가 이미 존재합니다.');copy.nodes.push(node);items.forEach((item,i)=>connectTyped(copy,rootGraph,item.node,item.output??'out',node.id,ports[i],node.id+'_wire_'+i));created.push(node);}graph.nodes=copy.nodes;graph.edges=copy.edges;return created;}
export function typedScopes(graph){const found=[];const visit=(body,path)=>{found.push([path,body]);for(const node of body.nodes??[])if(node.kind==='cases')for(const branch of node.branches??[])visit(branch,path+'/'+node.id+'/'+branch.id);};visit(graph,'root');for(const module of graph.modules??[])visit(module,'module/'+module.id);return found;}
export function copyTyped(scope,ids,identity){const chosen=new Set(ids),nodes=scope.nodes.filter(n=>chosen.has(n.id));if(!nodes.length)throw new Error('복사할 블록을 선택하세요.');return{version:1,identity:structuredClone(identity),nodes:structuredClone(nodes),edges:structuredClone(scope.edges.filter(e=>chosen.has(e.source)&&chosen.has(e.target)))};}
export function pasteTyped(scope,root,clipboard,identity,allocate){
 if(!clipboard||clipboard.identity.documentId!==identity.documentId||clipboard.identity.scopeId!==identity.scopeId)throw new Error('같은 문서·의미 범위에만 블록을 붙여넣을 수 있습니다.');
 const count=bodies=>bodies.reduce((sum,[,b])=>({nodes:sum.nodes+b.nodes.length,edges:sum.edges+b.edges.length}),{nodes:0,edges:0}),current=count(typedScopes(root)),addition=count(typedScopes({...clipboard,modules:[]}));
 if(current.nodes+addition.nodes>256||current.edges+addition.edges>512)throw new Error('붙여넣기가 문서의 256개 노드·512개 연결 한도를 초과합니다.');
 const copied=structuredClone({nodes:clipboard.nodes,edges:clipboard.edges}),used=new Set(scope.nodes.map(n=>n.id));
 function fresh(kind){const id=allocate(kind);if(typeof id!=='string'||used.has(id))throw new Error('새 블록 ID가 중복되었습니다.');used.add(id);return id;}
 function rename(body){const ids=new Map();for(const node of body.nodes){const original=node.id;node.id=fresh('paste');ids.set(original,node.id);node.x=(node.x??0)+30;node.y=(node.y??0)+30;if(node.kind==='cases')for(const branch of node.branches){branch.id=fresh('branch');rename(branch);}}
  for(const edge of body.edges){edge.id=fresh('wire');edge.source=ids.get(edge.source);edge.target=ids.get(edge.target);}if(body.result)body.result.node=ids.get(body.result.node);
 }
 rename(copied);scope.nodes.push(...copied.nodes);scope.edges.push(...copied.edges);return copied.nodes;
}
export function editSignature(graph,id,inputs,outputType){const definition=graph.modules.find(m=>m.id===id);if(!definition)throw new Error('함수 정의가 없습니다.');const affected=new Set([id]),scopes=typedScopes(graph);let changed=true;while(changed){changed=false;for(const module of graph.modules)if(!affected.has(module.id)&&scopes.filter(([path])=>path==='module/'+module.id||path.startsWith('module/'+module.id+'/')).some(([,body])=>body.nodes.some(n=>n.kind==='module'&&affected.has(n.ref)))){affected.add(module.id);changed=true;}}const calls=[];for(const [path,scope] of scopes)for(const node of scope.nodes)if(node.kind==='module'&&affected.has(node.ref))calls.push(path+'/'+node.id);definition.inputs=structuredClone(inputs);definition.outputType=outputType;return calls;}
export function typedDemo(){return{version:3,name:'Nat · LeanScript',projectId:'glean',imports:[],policy:'standard',inputs:[{id:'n',name:'n',type:'Nat'}],goal:'n + 0 = n',modules:[],nodes:[{id:'n',kind:'input',ref:'n',x:50,y:100},{id:'zero',kind:'script',name:'add_zero',inputs:[{id:'x',name:'x',type:'Nat'}],outputType:'x + 0 = x',body:'by rfl',x:330,y:100}],edges:[{id:'wire',source:'n',output:'out',target:'zero',input:'x'}],result:{node:'zero',output:'out'}};}
export function typedCompatibility(actual,expected){if(typeof actual!=='string'||typeof expected!=='string')return 'unknown';if(actual===expected)return 'compatible';const rigid=new Set(['Nat','Int','Bool','String','Char','Prop']);return rigid.has(actual)&&rigid.has(expected)?'incompatible':'unknown';}
