// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import {setManualHidden,createContainer,descendantNodes,projectScope} from './presentation.mjs';
const el=(tag,text,className='')=>{const n=document.createElement(tag);n.className=className;if(text!==undefined)n.textContent=text;return n;};
export function diagnosticVisibility(diagnostics,scope,graph,view){
 const counts={inside:0,outside:0,unknown:0};for(const d of diagnostics){if(d.severity!=='error')continue;let id=d.nodeId;const location=d.graphLocation;if(location){if(!location.startsWith(scope+'/')){counts.outside++;continue;}id=graph.nodes.find(n=>location===scope+'/'+n.id||location.startsWith(scope+'/'+n.id+'/'))?.id;}if(!id){counts.unknown++;continue;}counts[view.visibleIds.includes(id)?'inside':'outside']++;}return counts;
}
export function manuallyHidden(p,id){return p.hidden.includes('n:'+id)||p.containers.some(c=>p.hidden.includes('c:'+c.id)&&descendantNodes(p,'c:'+c.id).includes(id));}
export function directExpansion(body,p,entities,direction,references){
 const valid=new Set(body.nodes.map(n=>n.id)),selected=[...new Set(entities.flatMap(e=>descendantNodes(p,e)))].filter(id=>valid.has(id));
 const found=references?references(selected,direction):{ids:body.edges.filter(e=>direction==='inputs'?selected.includes(e.target):selected.includes(e.source)).map(e=>direction==='inputs'?e.source:e.target),unresolved:[]};
 const candidates=[...new Set(found.ids)].filter(id=>valid.has(id)&&!selected.includes(id));
 return{selected,additions:candidates.filter(id=>!manuallyHidden(p,id)),hidden:candidates.filter(id=>manuallyHidden(p,id)),unresolved:[...new Set(found.unresolved??[])],relation:references?'소스 상수 직접 참조':'정적 포트 연결',sourceUnknown:references?found.unknown===true:selected.some(id=>['script','construct','calc','cases'].includes(body.nodes.find(n=>n.id===id).kind))};
}
export function initVisibilityTools({host,body,presentation,session,key,semanticScope=key,recovery=()=>false,resume=()=>{},selection,viewport,setViewport,edit,refresh,focus,ports,references,diagnostics=()=>[],fit=()=>{},error=()=>{}}){
 let query='',menuOpen=false,listOpen=false,contextPoint=null,expansion=null;
 const button=(text,fn,disabled=false,closeMenu=false)=>{const b=el('button',text,'button quiet small');b.type='button';b.disabled=disabled;b.addEventListener('click',()=>{try{fn();if(closeMenu){menuOpen=false;contextPoint=null;for(const node of host.children)if(node.className==='visibility-menu')node.open=false;}}catch(e){error(e);}});return b;};
 function render(){
  const graph=body();if(!graph)return;const p=presentation(),scope=key(),state=session.state(scope);session.prune(scope,graph,p);const view=projectScope(graph,p,state,ports?.());
  host.replaceChildren();host.className='visibility-tools';
  const menu=el('details',undefined,'visibility-menu'),summary=el('summary','보기 ▾');menu.open=menuOpen;menu.addEventListener('toggle',()=>menuOpen=menu.open);menu.append(summary);
  const commands=el('div',undefined,'visibility-commands'),selected=selection();
  if(contextPoint)Object.assign(commands.style,{position:'fixed',left:Math.max(4,Math.min(contextPoint.x,(globalThis.innerWidth??1000)-250))+'px',top:Math.max(4,Math.min(contextPoint.y,(globalThis.innerHeight??700)-220))+'px'});
  commands.append(button('선택 숨기기',()=>{setManualHidden(p,state,selection(),true);edit();refresh();},!selected.length,true),button('선택만 보기',()=>{session.isolate(scope,graph,p,selection(),viewport());refresh();},!selected.length,true),button('수동 숨김 해제',()=>{p.hidden=[];edit();refresh();},false,true),button('현재 캔버스 전부 표시',()=>{p.hidden=[];session.exit(scope);edit();refresh();},false,true),button('그룹으로 묶기',()=>{const id='container_'+crypto.randomUUID().slice(0,8);createContainer(graph,p,selection(),{id,name:'그룹 '+(p.containers.length+1)});edit();refresh();},!selected.length,true));
  for(const [direction,label] of [['inputs','선택 + 직접 입력 보기'],['users','선택 + 직접 사용처 보기']])commands.append(button(label,()=>{expansion={...directExpansion(graph,p,selection(),direction,references),scope};session.isolate(scope,graph,p,[...expansion.selected,...expansion.additions].map(id=>'n:'+id),viewport());refresh();},!selected.length,true));
  menu.append(commands);host.append(menu);if(recovery())host.append(button('이전 격리 복원',resume));
  if(expansion?.scope===scope&&state.frames.length){host.append(el('span',`${expansion.relation} · 직접 추가 ${expansion.additions.length}개 · 수동 숨긴 관련 ${expansion.hidden.length}개${expansion.unresolved.length?' · 범위 밖 참조 '+expansion.unresolved.length+'개':''}${expansion.sourceUnknown?' · 본문 소스 참조 미확정':''}`,'isolation-status'));if(expansion.hidden.length)host.append(button('숨긴 관련 항목 명시적으로 추가',()=>{session.add(scope,graph,p,expansion.hidden.map(id=>'n:'+id),true);expansion={...expansion,additions:[...expansion.additions,...expansion.hidden],hidden:[]};refresh();}));if(expansion.unresolved.length){const note=el('details',undefined,'visibility-menu');note.append(el('summary','범위 밖 소스 참조'),el('pre',expansion.unresolved.join('\n')));host.append(note);}}
  else expansion=null;
  const list=el('details',undefined,'visibility-menu hidden-list'),heading=el('summary','숨긴 항목 '+view.hiddenIds.length+'개');list.open=listOpen;list.addEventListener('toggle',()=>listOpen=list.open);list.append(heading);const panel=el('div',undefined,'visibility-commands'),search=el('input');search.type='search';search.placeholder='이름·종류로 찾기';search.value=query;search.setAttribute('aria-label','숨긴 항목 검색');
  const items=el('div',undefined,'hidden-list-items');function fill(){items.replaceChildren();for(const id of view.hiddenIds){const n=graph.nodes.find(n=>n.id===id);if(!((n.name??id)+' '+n.kind).toLowerCase().includes(query.toLowerCase()))continue;const row=el('div',undefined,'hidden-list-row');const reason=manuallyHidden(p,id)?'수동 숨김':state.frames.length?'격리 밖 / 접힌 내부':'접힌 내부';row.append(el('span',(n.name??id)+' · '+n.kind+' · '+reason),button('찾기',()=>focus(id)),button(state.frames.length?'대상 추가':'다시 표시',()=>{if(state.frames.length)session.add(scope,graph,p,['n:'+id],true);else{setManualHidden(p,state,['n:'+id],false);for(const c of p.containers)if(descendantNodes(p,'c:'+c.id).includes(id)){p.hidden=p.hidden.filter(k=>k!=='c:'+c.id);c.collapsed=false;}edit();}refresh();}));items.append(row);}}
  search.addEventListener('input',()=>{query=search.value;fill();});fill();panel.append(search,items);list.append(panel);host.append(list);
  if(state.frames.length){const counts=diagnosticVisibility(diagnostics(),semanticScope(),graph,view);const status=el('span',`${semanticScope()} · 격리 ${state.frames.length}단계 · 대상 ${state.frames.at(-1).targets.length} · 격리 숨김 ${view.isolationHiddenCount} · 수동 숨김 설정 ${view.manualHiddenCount}${view.visibleIds.filter(id=>manuallyHidden(p,id)).length?' (임시 표시 '+view.visibleIds.filter(id=>manuallyHidden(p,id)).length+')':''} · 밖 오류 ${counts.outside}${counts.unknown?' · 위치 미확정 '+counts.unknown:''}`,'isolation-status');status.setAttribute('role','status');host.append(status,button('선택에 맞추기',fit),button('이전 격리로',()=>{const v=session.back(scope);if(v)setViewport(v);refresh();},state.frames.length<2),button('격리 종료',()=>{const v=session.exit(scope);if(v)setViewport(v);refresh();}));}
  if(!view.visibleIds.length&&graph.nodes.length)host.append(el('span','표시할 대상이 없습니다. 숨긴 항목에서 다시 표시하거나 격리를 종료하세요.','isolation-empty'));
  if(state.temporary.nodes.length)host.append(el('span','진단 위치 임시 표시','isolation-status'),button(state.frames.length?'격리로 돌아가기':'임시 표시 끝내기',()=>{const v=session.clearTemporary(scope);if(v)setViewport(v);refresh();}),button('계속 표시',()=>{const ids=[...state.temporary.nodes];for(const id of ids){setManualHidden(p,state,['n:'+id],false);for(const c of p.containers)if(descendantNodes(p,'c:'+c.id).includes(id)){p.hidden=p.hidden.filter(k=>k!=='c:'+c.id);c.collapsed=false;}}if(state.frames.length)session.add(scope,graph,p,ids.map(id=>'n:'+id));session.clearTemporary(scope);edit();refresh();}));
 }
 return{render,contextMenu(event){event.preventDefault();menuOpen=true;contextPoint={x:event.clientX,y:event.clientY};render();},back(){const scope=key(),v=session.back(scope);if(v){setViewport(v);refresh();return true;}return false;}};
}
