// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {Element,descendants,find} from './audit_dom_harness.mjs';
import {initSourceAnalysis} from '../../prototype/web/source-analysis.mjs';
import {DocumentHistory,semanticKey} from '../../prototype/web/history.mjs';
import {canReuseVerifiedResult} from '../../prototype/web/proof-review.mjs';
import {validateIsolation,IsolationRecoveryStore} from '../../prototype/web/isolation-recovery.mjs';
const app=fs.readFileSync(new URL('../../prototype/web/app.js',import.meta.url),'utf8'),start=app.indexOf('async function navigateHistory('),end=app.indexOf('\nfunction renderNotebook',start),actual=JSON.parse(fs.readFileSync(new URL('design-audit-command-product-retest.json',import.meta.url))),source=fs.readFileSync(new URL('design-audit-command-fixture.lean',import.meta.url),'utf8');assert.ok(start>=0&&end>start);
const cases=[];
for(const scenario of [{id:'same-env-preserves-actual-source-frame',environment:{environmentHash:'same'},expect:true},{id:'changed-env-clears-old-result',environment:{environmentHash:'different'},expect:false},{id:'missing-env-clears-old-result',environment:{},expect:false},{id:'late-env-after-new-check-discarded',environment:{environmentHash:'same'},expect:false,late:true}]){
 globalThis.document={createElement:tag=>new Element(tag)};let doc={kind:'lean',source,filename:actual.filename,projectId:actual.projectId,target:'Scoped.from_macro',policy:'standard'},context;
 const history=new DocumentHistory(),host=new Element(),status=new Element(),run=new Element('button'),cancel=new Element('button'),delivered=[],requests=[];let requested=false,resolve;
 history.reset(doc);
 const panel=initSourceAnalysis({host,status,run,cancel,current:()=>doc,jump(){},onCache:cache=>{doc.analysisCache=cache;history.commit(doc);},onReference(){},onView:value=>{doc.sourceFileView=value;if(!context?.restoring)history.commit(doc);},post:async(path,body)=>{requests.push({path,body});return actual;}});
 const click=async label=>{const n=find(host,n=>n.tagName==='button'&&n.textContent===label);assert.ok(n&&!n.disabled,'command '+label);await n.fire('click');};
 const select=async name=>{const n=find(host,n=>n.tagName==='input'&&n['aria-label']===name+' 선택');assert.ok(n);await n.fire('click');};
 try{
  await run.fire('click');await select('Scoped.generated');await click('선택 숨기기');await select('Scoped.from_macro');await click('선택만 보기');const beforeIsolation=panel.isolationSnapshot(),beforeDoc=structuredClone(doc);await click('선택 숨기기');const original={status:'valid',verified:true,target:doc.target,environment:{environmentHash:'same'},audit:{axioms:[]}};
  context={mode:'lean',sourceAnalysis:panel,currentDocument:()=>structuredClone(doc),result:original,activeModuleId:null,view:{x:20,y:20,zoom:1},typedEditor:{presentation:()=>null},history,restoring:false,formDirty:false,verificationEpoch:0,semanticKey,canReuseVerifiedResult,validateIsolation,loadDocument(value){doc=structuredClone(value);context.result=null;context.verificationEpoch++;panel.loadCache(doc.analysisCache);},updateHistoryButtons(){},persistDraft(){},$:()=>({value:'all'}),renderLeanResult(value){delivered.push(value);context.result=value;},toast(){},fetch(){requested=true;return scenario.late?new Promise(r=>resolve=r):Promise.resolve({ok:true,json:async()=>scenario.environment});}};
  vm.createContext(context);vm.runInContext(app.slice(start,end),context);const pending=context.navigateHistory();if(scenario.late){while(!requested)await new Promise(r=>setTimeout(r,0));context.verificationEpoch++;context.result={status:'invalid',verified:false};resolve({ok:true,json:async()=>scenario.environment});}await pending;
  assert.deepEqual(doc,beforeDoc);assert.equal(doc.source,source);assert.deepEqual(panel.isolationSnapshot(),beforeIsolation);assert.ok(find(host,n=>n.tagName==='input'&&n['aria-label']==='Scoped.from_macro 선택'));assert.equal(delivered.length,scenario.expect?1:0);assert.equal(context.result?.verified??false,scenario.expect);assert.equal(requests.length,1);
  if(scenario.expect){
   const saved=panel.isolationSnapshot(),memory=new Map(),store=new IsolationRecoveryStore({storage:{getItem:key=>memory.get(key)??null,setItem:(key,value)=>memory.set(key,value)}});assert.equal(store.save('source-doc',saved),true);const loaded=store.load('source-doc',doc);assert.ok(loaded);panel.loadCache(doc.analysisCache);assert.ok(!Object.keys(panel.isolationSnapshot().views).length);panel.offerIsolationRecovery(loaded);assert.ok(!Object.keys(panel.isolationSnapshot().views).length);await click('이전 격리 복원');assert.deepEqual(panel.isolationSnapshot(),saved);assert.ok(!JSON.stringify(doc).includes('frames'));const other={...doc,analysisCache:{...doc.analysisCache,declarations:[]}};assert.equal(store.load('source-doc',other),null);
  }
  cases.push({id:scenario.id,pass:true,sourceExact:true,isolationAndSelectionExact:true,additionalAnalysisRequests:0,reusedVerified:context.result?.verified??false,explicitSeparateRecovery:scenario.expect||undefined});
 }catch(error){cases.push({id:scenario.id,pass:false,error:error.stack});}finally{panel.close();}
}
const report={kind:'actual source-analysis visibility/real DocumentHistory/actual app navigateHistory callback; saved actual command metadata; controlled DOM/environment/proof-result solely for reuse/race; no native UI or new Lean',hashes:Object.fromEntries(['app.js','source-analysis.mjs','source-view.mjs','isolation-recovery.mjs'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(new URL('../../prototype/web/'+name,import.meta.url))).digest('hex')])),cases,pass:cases.every(c=>c.pass)};fs.writeFileSync(new URL(process.argv[2]??'source-history-results.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.pass?0:1;
