// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';
import {harness,find} from './audit_dom_harness.mjs';
import {validateIsolation,IsolationRecoveryStore} from '../../prototype/web/isolation-recovery.mjs';
import {semanticKey} from '../../prototype/web/history.mjs';
const app=fs.readFileSync(new URL('../../prototype/web/app.js',import.meta.url),'utf8'),cases=[];
const start=app.indexOf('async function navigateHistory('),end=app.indexOf('\nfunction renderNotebook',start);assert.ok(start>=0&&end>start);
async function probe(id,fn){try{cases.push({id,pass:true,...await fn()});}catch(e){cases.push({id,pass:false,error:e.message});}}
await probe('actual-app-undo-retains-current-isolation-and-manual-hidden-state',async()=>{const h=harness();try{h.editor.jumpKey('root/spare');await h.click('선택 숨기기');h.editor.jumpKey('root/zero');await h.click('선택만 보기');await h.click('선택 숨기기');const beforeIsolation=h.editor.isolationSnapshot(),nodes=new Map();const context={mode:'typed',currentDocument:()=>h.editor.current(),result:null,activeModuleId:null,view:{x:20,y:20,zoom:1},typedEditor:h.editor,history:h.history,restoring:false,loading:false,formDirty:false,semanticKey,validateIsolation,verificationEpoch:0,loadDocument:doc=>h.editor.open(doc),updateHistoryButtons(){},persistDraft(){},$:id=>{if(!nodes.has(id))nodes.set(id,{value:'all'});return nodes.get(id);},toast(){}};vm.createContext(context);vm.runInContext(app.slice(start,end)+'\npending=navigateHistory();',context);await context.pending;const current=h.editor.current(),afterIsolation=h.editor.isolationSnapshot();assert.deepEqual(afterIsolation,beforeIsolation);assert.deepEqual(current.presentation.scopes.root.hidden,['n:spare']);assert.ok(find(h.host,n=>n.tagName==='article'&&n.dataset.id==='zero'));assert.ok(find(h.host,n=>n.className==='isolation-status'&&n.textContent.includes('대상 1')));return {hidden:current.presentation.scopes.root.hidden,isolation:afterIsolation};}finally{h.editor.close();}});
await probe('actual-explicit-resume-with-current-target-validation',async()=>{const h=harness();try{h.editor.jumpKey('root/zero');await h.click('선택만 보기');const saved=h.editor.isolationSnapshot(),doc=h.editor.current();h.editor.open(doc);assert.ok(!find(h.host,n=>n.className==='isolation-status'));h.editor.offerIsolationRecovery(saved);assert.ok(!find(h.host,n=>n.className==='isolation-status'));await h.click('이전 격리 복원');assert.ok(find(h.host,n=>n.className==='isolation-status'));assert.deepEqual(h.editor.isolationSnapshot(),saved);return {resumedOnlyAfterExplicitClick:true};}finally{h.editor.close();}});
await probe('separate-store-document-target-and-viewport-guards',async()=>{const h=harness();try{h.editor.jumpKey('root/zero');await h.click('선택만 보기');const doc=h.editor.current(),saved=h.editor.isolationSnapshot(),memory=new Map(),store=new IsolationRecoveryStore({storage:{getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v)}}),before=JSON.stringify(doc);assert.equal(store.save('doc-A',saved),true);assert.equal(store.load('doc-B',doc),null);assert.deepEqual(store.load('doc-A',doc).views.root.frames,saved.views.root.frames);const missing=structuredClone(doc);missing.graph.nodes=missing.graph.nodes.filter(n=>n.id!=='zero');assert.equal(store.load('doc-A',missing),null);const malformed=structuredClone(saved);malformed.views.root.frames[0].viewport.zoom=0;assert.deepEqual(validateIsolation(malformed,doc).views,{});assert.equal(JSON.stringify(doc),before);assert.ok(!JSON.stringify(doc).includes('frames'));return {differentDocumentRejected:true,missingTargetRejected:true,malformedViewportRejected:true,ordinaryDocumentUnchanged:true};}finally{h.editor.close();}});
await probe('explicit-session-resume-restores-nested-navigation-selection-and-view',async()=>{const h=harness();try{const doc=JSON.parse(fs.readFileSync(new URL('ui-mixed-3-level.json',import.meta.url),'utf8'));h.editor.open(doc);await h.click('내부 열기',find(h.host,n=>n.tagName==='article'&&n.dataset.id==='callA'));h.editor.jumpKey('module/outer/n_in');await h.click('선택만 보기');const before=h.editor.presentation(),snapshot=h.editor.isolationSnapshot(),saved=h.editor.current();h.editor.open(saved);h.editor.offerIsolationRecovery(snapshot);await h.click('이전 격리 복원');const after=h.editor.presentation();const sameNavigation=JSON.stringify(before.path)===JSON.stringify(after.path)&&JSON.stringify(before.trail)===JSON.stringify(after.trail)&&before.selected===after.selected&&JSON.stringify(before.view)===JSON.stringify(after.view);cases.push({id:'nested-navigation-resume-observation',pass:sameNavigation,before,after});assert.ok(sameNavigation,'explicit restore retains child frame but loses child path, selection and viewport');return {sameNavigation};}finally{h.editor.close();}});
await probe('child-undo-preserves-parent-return-navigation-history',async()=>{const h=harness();try{const doc=JSON.parse(fs.readFileSync(new URL('ui-mixed-3-level.json',import.meta.url),'utf8'));h.editor.open(doc);h.history.reset(h.editor.current());const rootView=h.editor.presentation().view;await h.click('내부 열기',find(h.host,n=>n.tagName==='article'&&n.dataset.id==='callA'));h.editor.jumpKey('module/outer/n_in');assert.ok(find(h.host,n=>n.tagName==='button'&&n.textContent==='상위로 돌아가기'));await h.click('선택 숨기기');const nodes=new Map(),context={mode:'typed',currentDocument:()=>h.editor.current(),result:null,activeModuleId:null,view:{x:20,y:20,zoom:1},typedEditor:h.editor,history:h.history,restoring:false,loading:false,formDirty:false,semanticKey,validateIsolation,verificationEpoch:0,loadDocument:doc=>h.editor.open(doc),updateHistoryButtons(){},persistDraft(){},$:id=>{if(!nodes.has(id))nodes.set(id,{value:'all'});return nodes.get(id);},toast(){}};vm.createContext(context);vm.runInContext(app.slice(start,end)+'\npending=navigateHistory();',context);await context.pending;const parentReturnAvailable=!!find(h.host,n=>n.tagName==='button'&&n.textContent==='상위로 돌아가기');assert.ok(parentReturnAvailable,'Undo in a valid child scope removes the parent-return navigation history');await h.click('상위로 돌아가기');assert.deepEqual(h.editor.presentation().path,[]);assert.deepEqual(h.editor.presentation().view,rootView);return {parentReturnAvailable,rootViewportRestored:true};}finally{h.editor.close();}});
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(new URL(file,import.meta.url))).digest('hex');
const result={kind:'actual typed event + actual app history callback / controlled DOM; separate model/store controls; not native UI or kernel',hashes:{app:sha('../../prototype/web/app.js'),typedEditor:sha('../../prototype/web/typed-editor.mjs'),isolationRecovery:sha('../../prototype/web/isolation-recovery.mjs')},cases};fs.writeFileSync(new URL(process.argv[2]??'isolation-recovery-navigation-results.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));process.exitCode=cases.every(c=>c.pass)?0:1;
