// Copyright (c) 2026 GLEAN contributors. Released under Apache 2.0.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {Element,descendants,find} from './audit_dom_harness.mjs';
import {initSourceAnalysis} from '../../prototype/web/source-analysis.mjs';
import {semanticKey} from '../../prototype/web/history.mjs';
import {sourceScope} from '../../prototype/web/source-view.mjs';
const actual=JSON.parse(fs.readFileSync(new URL('design-audit-command-product-retest.json',import.meta.url)));
assert.equal(actual.status,'analyzed');assert.equal(actual.verified,false);
let doc={kind:'lean',source:fs.readFileSync(new URL('design-audit-command-fixture.lean',import.meta.url),'utf8'),filename:actual.filename,projectId:actual.projectId};
globalThis.document={createElement:tag=>new Element(tag)};
const host=new Element(),status=new Element(),run=new Element('button'),cancel=new Element('button'),fileCard=new Element(),jumps=[],requests=[],views=[],warnings=[];
const panel=initSourceAnalysis({host,status,run,cancel,fileCard,current:()=>doc,jump:(...args)=>jumps.push(args),onCache:cache=>doc.analysisCache=cache,onReference(){},onView:view=>{views.push(view);doc.sourceFileView=view;},onWarning:value=>warnings.push(value),post:async(path,body)=>{requests.push({path,body});assert.equal(path,'/api/lean/index/start');return actual;}});
const click=async label=>{const n=find(host,n=>n.tagName==='button'&&n.textContent===label);assert.ok(n,'missing '+label);assert.ok(!n.disabled,'disabled '+label);await n.fire('click');};
const choose=async name=>{const box=find(host,n=>n.tagName==='input'&&n.type==='checkbox'&&n['aria-label']===name+' 선택');assert.ok(box,'missing selection '+name);await box.fire('click');};
let report;
try{
 await run.fire('click');const key=semanticKey(doc),proofName='Scoped.from_macro',dependency='Scoped.generated';assert.ok(find(host,n=>n.className==='source-relation-legend'&&n.textContent.includes('목표 관측')&&n.textContent.includes('증명 포트 와이어')));
 await choose(dependency);await click('선택 숨기기');assert.deepEqual(doc.sourceFileView.presentation.scopes.root.hidden,['n:declaration:'+dependency]);
 await choose(proofName);await click('선택 + 직접 입력 보기');const initial=descendants(host).find(n=>n.className==='isolation-status'&&n.textContent.includes('소스 상수'));assert.ok(initial);assert.ok(initial.textContent.includes('직접 추가 0개'));assert.ok(initial.textContent.includes('수동 숨긴 관련 1개'));assert.ok(/(?:현재 파일 밖|범위 밖) 참조 1개/.test(initial.textContent));
 assert.deepEqual(panel.isolationSnapshot().views.root.frames.at(-1).targets,['declaration:'+proofName]);await click('숨긴 관련 항목 명시적으로 추가');assert.deepEqual(new Set(panel.isolationSnapshot().views.root.frames.at(-1).targets),new Set(['declaration:'+proofName,'declaration:'+dependency]));assert.deepEqual(doc.sourceFileView.presentation.scopes.root.hidden,['n:declaration:'+dependency]);
 assert.ok(find(host,n=>n.tagName==='pre'&&n.textContent=== 'Nat'));await click('격리 종료');assert.deepEqual(doc.sourceFileView.presentation.scopes.root.hidden,['n:declaration:'+dependency]);await click('수동 숨김 해제');await choose(dependency);await click('선택 + 직접 사용처 보기');const users=panel.isolationSnapshot().views.root.frames.at(-1).targets;assert.deepEqual(new Set(users),new Set(['declaration:'+dependency,'declaration:Scoped.from_macro','declaration:Scoped.valid_after_error']));assert.equal(sourceScope(doc,actual.declarations).edges.length,0);assert.equal(semanticKey(doc),key);assert.equal(requests.length,1);
 await click('격리 종료');doc.source+='\n-- independent identity edit\n';panel.invalidate();assert.ok(status.textContent.includes('위치 대응 미확정'));const jumpButtons=descendants(host).filter(n=>n.tagName==='button'&&n.textContent==='원문 위치');assert.ok(jumpButtons.length>0&&jumpButtons.every(n=>n.disabled));assert.ok(find(host,n=>n.className==='source-analysis-summary'&&n.textContent.includes('저장된 과거 분석')));assert.ok(find(host,n=>n.tagName==='button'&&n.textContent===dependency+' · 저장된 분석'));assert.ok(!find(host,n=>n.tagName==='button'&&n.textContent===dependency+' · 현재 파일'));await choose(proofName);await click('선택 + 직접 입력 보기');assert.ok(find(host,n=>n.className==='isolation-status'&&n.textContent.includes('본문 소스 참조 미확정')));
 report={kind:'actual source-analysis visibility callbacks consuming saved independently obtained actual command-state metadata; controlled DOM/start response; no native UI/new Lean',pass:true,sourceMetadataHash:crypto.createHash('sha256').update(fs.readFileSync(new URL('design-audit-command-product-retest.json',import.meta.url))).digest('hex'),actualInputStatus:initial.textContent,directUsers:users,fullSourceAndSemanticKeyPreservedDuringVisibility:true,realProofEdges:0,analysisRequestsOnly:requests.length,viewCommits:views.length,historicalJumpsDisabledAfterSourceEdit:true,historicalLocalDependencyLabel:true,historicalRelationshipExplicitUnknown:true,warnings};
}catch(error){report={pass:false,error:error.stack};}finally{panel.close();}
report.productHashes=Object.fromEntries(['source-analysis.mjs','source-view.mjs','visibility-tools.mjs'].map(name=>[name,crypto.createHash('sha256').update(fs.readFileSync(new URL('../../prototype/web/'+name,import.meta.url))).digest('hex')]));fs.writeFileSync(new URL(process.argv[2]??'source-expansion-results.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exitCode=report.pass?0:1;
